let motosJson = [
	{
        id: 0,
        model: 'Harley-Davidson 883 R',
        year: '2011',
        price: '35500',
        kms: '90 mil km rodados',
        description: 'Cor azul • Tanque elevado • Bobina recolocada na lateral • Escape original',
        sell: 'no',
        credit: 'Troca FIPE x FIPE | Entrada facilitada em até 18x | Parcelamos sua moto em até 48x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
    {
        id: 1,
        model: 'Harley-Davidson Ultra Glide 1700cc',
        year: '2014',
        price: '83900',
        kms: '32 mil km rodados',
        description: 'IPVA 2024 pago • Documentação ok • Com multimídia • Pneus novos 21" • Alarme original HD • Roda dianteira Spoke 21" • Escape Vance Hanes • Guidão Diablo • Possui Tour Bag • Motocicleta com customização leve',
        sell: 'no',
        credit: 'Aceitamos moto ou carro na troca | Entrada facilitada em até 18x | Parcelamos sua moto em até 48x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
    {
        id: 2,
        model: 'Harley-Davidson 883 R',
        year: '2007',
        price: '33900',
        kms: '50 mil km rodados',
        description: 'Tanque elevado • Escape original barulhento com manta térmica • Guidão 7" • Comando avançado • Placa I',
        sell: 'no',
        credit: 'Aceitamos moto ou carro na troca | Entrada facilitada em até 18x | Parcelamos sua moto em até 48x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
    {
        id: 3,
        model: 'Harley-Davidson 883 R',
        year: '2007',
        price: '33900',
        kms: '43 mil km rodados',
        description: 'Tanque de maior capacidade • Escape barulhento com manta térmica • Guidão original • Carenagem do farol • Pneus novos • Documentação ok',
        sell: 'no',
        credit: 'Aceitamos moto ou carro na troca | Entrada facilitada em até 18x | Parcelamos sua moto em até 48x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
    {
        id: 4,
        model: 'Honda Shadow 600cc',
        year: '2003',
        price: '24500',
        kms: '99 mil km rodados',
        description: 'Escape original • Bateria nova',
        sell: 'no',
        credit: 'Aceitamos moto ou carro na troca | Entrada facilitada em até 18x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
	{
        id: 5,
        model: 'Harley-Davidson Sportster IRON 883',
        year: '2013',
        price: '38500',
        kms: '46 mil km rodados',
        description: 'Tanque elevado • Punhos customizados • Escape esportivo • Guidão 7"',
        sell: 'no',
        credit: 'Entrada facilitada em até 18x | Parcelamos sua moto em até 48x | Fazemos aprovação de crédito na hora e também por WhatsApp </br> 💳 Trabalhamos com todos os cartões de crédito em até 18x com taxas competitivas no mercado 💳',
    },
];